spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:mysql://localhost:3306/mydatabase
    username: myuser
    password: secret
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

  mail:
    sender:
    host:
    port:
    username:
    password:

  docker:
    compose:
      enabled: true
      file: docker/dev/compose.yaml

logging:
  level:
    org.springframework.security: DEBUG

jwt:
  secret: xin_chao_ban!_day_la_du_an_uit_land_cho_do_an_1_cua_minh!_xin_cam_on_ban_da_doc_du_an_nay
  refresh-token:
    expiration: 172800
  access-token:
    expiration: 18000

app:
  client:
    base-url: http://localhost:3000
