spring:
  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update

  docker:
    compose:
      enabled: false
  mail:
    sender: ${MAIL_SENDER}
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}

logging:
  level:
    org.springframework.security: DEBUG

jwt:
  secret: ${JWT_SECRET}
  refresh-token:
    expiration: ${JWT_REFRESH_TOKEN_EXPIRATION}
  access-token:
    expiration: ${JWT_ACCESS_TOKEN_EXPIRATION}

app:
  client:
    base-url: ${FRONTEND_BASE_URL}

# Payment Gateway Configuration
payment:
  return-url: ${PAYMENT_RETURN_URL}
  # VNPay Payment Configuration
  vnpay:
    url: https://vnpayment.vn/qr
    apiUrl: https://api.vnpayment.vn/merchant_webapi/api/transaction
    tmnCode: ${VNPAY_TMN_CODE}
    secretKey: ${VNPAY_SECRET_KEY}
    version: "2.1.0"
    command: pay
    orderType: billpayment
    expiredTime: 15
    returnUrl: ${VNPAY_RETURN_URL}
  # ZaloPay Payment Configuration
  zalopay:
    app-id: ${ZALOPAY_APP_ID}
    key1: ${ZALOPAY_KEY1}
    key2: ${ZALOPAY_KEY2}
    url: https://api.zalopay.vn/v2/create
    redirect-url: https://zalopay.vn/web/payment/paymentpage.html

