spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:mysql://localhost:3306/mydatabase
    username: myuser
    password: secret
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

  mail:
    sender:
    host:
    port:
    username:
    password:

  docker:
    compose:
      enabled: true
      file: docker/dev/compose.yaml
  kafka:
    bootstrap-servers: localhost:9092

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

    consumer:
      group-id: se100-backend
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "uit.se100.*"

logging:
  level:
    org.springframework.security: DEBUG

jwt:
  secret: xin_chao_ban!_day_la_du_an_uit_land_cho_do_an_1_cua_minh!_xin_cam_on_ban_da_doc_du_an_nay
  refresh-token:
    expiration: 172800
  access-token:
    expiration: 18000

app:
  client:
    base-url: http://localhost:3000

payment:
  vnPay:
    url:
      ${VNPAY_URL:https://sandbox.vnpayment.vn/paymentv2/vpcpay.html}
    returnUrl: ${VNPAY_RETURN_URL:http://localhost:8080/api/v1/payments/vnpay-callback}
    tmnCode: ${VNPAY_TMN_CODE}
    secretKey: ${VNPAY_SECRET_KEY}
    expiredTime: 15 #minutesw